### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/pos#123]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0
# Modules to migrate
- [ ] hw_customer_display
- [ ] hw_telium_payment_terminal
- [ ] pos_cash_move_reason - by @GillesTephaneMeyomesse #177
- [x] pos_customer_display - By @alexis-via - #126 
- [ ] pos_gift_ticket - By @spacemonkeythe - #221 
- [ ] pos_order_load - By @cvinh - #244 
- [x] pos_payment_terminal - By @alexis-via - #124 
- [x] pos_pricelist - ~~By @spacemonkeythe - #220~~ Backport from v11 - By @Yajo - #247 
- [x] pos_price_to_weight - By @invitu -  #224 
- [x] pos_product_template - ~~By @hparfr - #266~~ - By @hparfr - #271 
- [x] pos_remove_pos_category - By @simahawk - #148

**Comment by alexis-via** [comment]
Migration of pos_customer_display here: https://github.com/OCA/pos/pull/126

**Comment by innowintay** [comment]
Any particular reason why pos_quick_logout isn't being considered for migration?

**Comment by pedrobaeza** [comment]
It has been merged in 9.0 after the creation of this issue

**Comment by odooerpperu** [comment]
Hi Pedro the migration of **pos_sequence_ref_number** to version 10, it has been considered?
Thank

**Comment by pedrobaeza** [comment]
Well, why not if someone do it. It's not listed here because it was added to previous versions after the branch creation and thus the automatic issue creation didn't include it.

**Comment by TimLai125** [comment]
Hi @pedrobaeza , may I know if the migration of pos_pricelist to v10 is scheduled?

**Comment by pedrobaeza** [comment]
No, nobody has expressed their wish to migrate it, so as this is a voluntary work, nothing is planned for now.

**Comment by spacemonkeythe** [comment]
Migration of the pos_pricelist module [#220](https://github.com/OCA/pos/pull/220)

**Comment by spacemonkeythe** [comment]
Migration of the pos_gift_ticket module [#221](https://github.com/OCA/pos/pull/221)

**Comment by cvinh** [comment]
Migration of pos_order_load here https://github.com/OCA/pos/pull/244
