### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/pos#216]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [ ] ~account_cash_invoice - By @jbeficent - #217~ should be moved in accounting repository.
- [ ] hw_customer_display
- [ ] hw_telium_payment_terminal
- [ ] pos_customer_display - By @rupa-acespritech - #321 
- [ ] pos_default_empty_image
- [ ] pos_default_payment_method - By @CGenie - #316 
- [ ] pos_gift_ticket
- [x] pos_lot_selection - By @NachoAlesLopez - #285 
- [x] pos_loyalty - By @kirca - #288 
- [x] pos_margin - By @invitu - #298 
- [x] pos_order_return - By @kirca - #286 
- [x] pos_payment_entries_globalization - By @chienandalu - #325 
- [ ] pos_payment_terminal - By @invitu - #301 
- [ ] pos_picking_delayed - By @chienandalu - #386
- [x] ~~pos_pricelist~~ Not needed - Implemented in core.
- [ ] pos_product_template - By @hugosantosred - #284 
- [ ]  pos_quick_logout - By @akevinieron
- [ ] pos_remove_pos_category (Need refactor https://github.com/OCA/pos/issues/200#issuecomment-323671644)
- [x] pos_session_pay_invoice - By @jbeficent - #218 
- [x] pos_stock_picking_invoice_link - By @chienandalu - #376 
- [x] pos_ticket_logo - By @chienandalu - #300

**Comment by legalsylvain** [comment]
I updated account_cash_invoice line, regarding https://github.com/OCA/pos/pull/217#issuecomment-337903987. regards.

**Comment by gustavovalverde** [comment]
@pedrobaeza even though **pos_quick_logout** is not in this list, I think we still can migrate it right? If yes, @akevinieron will be working on it.

**Comment by pedrobaeza** [comment]
@gustavovalverde that's because it was put on previous branches after this branch creation, but of course it can be migrated. Please check if this feature is still needed before starting the work.

**Comment by hugosantosred** [comment]
pos_product_template on https://github.com/OCA/pos/pull/284

**Comment by NachoAlesLopez** [comment]
pos_lot_selection #285

**Comment by kirca** [comment]
pos_order_return in https://github.com/OCA/pos/pull/286

**Comment by kirca** [comment]
I'll do migration of **pos_loyalty** next

**Comment by SimoRubi** [comment]
module https://github.com/OCA/pos/tree/8.0/pos_invoice_journal doesn't need migration to v11 because its functionality has been included by https://github.com/odoo/odoo/commit/b5b0d36b31606e6c462a83080c66ec06b326ed45

**Comment by CGenie** [comment]
pos_default_payment_method #316

**Comment by emagdalenaC2i** [comment]
@pedrobaeza Please, check pos_loyalty - By @kirca - #288 because it is already merged

**Comment by Ark74** [comment]
Can we add to the ToDo list,

- [pos_default_empty_image](https://github.com/OCA/pos/tree/10.0/pos_default_empty_image)

Cheers!

**Comment by pedrobaeza** [comment]
OK, added.

**Comment by emagdalenaC2i** [comment]
Please check pos_margin - By @invitu - #298 that is already merged

Please check pos_ticket_logo - By @chienandalu - #300 that is already merged

**Comment by chienandalu** [comment]
Thanks, @emagdalenaC2i Done :)

**Comment by ivantodorovich** [comment]
> @pedrobaeza even though **pos_quick_logout** is not in this list, I think we still can migrate it right? If yes, @akevinieron will be working on it.

Hi @gustavovalverde, did you migrate this after all? is it WIP somewhere?
