### ISSUE TITLE
Migration to version 9.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/pos#58]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0
# Modules to migrate
- [ ] pos_payment_terminal - By @yuntux - #105 
- [ ] pos_gift_ticket
- [x] pos_customer_display - By @wamdam - #119 
- [ ] pos_pricelist - ~~By @x620 - #83~~ - By @wpichler - #186 
- [ ] hw_customer_display
- [ ] hw_telium_payment_terminal
- [ ] pos_remove_pos_category
- [ ] pos_product_template - Assigned to @navarromiguel - #97
- [ ] pos_default_empty_image
- [ ] pos_order_pricelist_change
- [x] pos_restricted_customer_list - By @ThomasBinsfeld - #343

**Comment by hviniciusg** [comment]
Hello Pedro, how can i help?

**Comment by pedrobaeza** [comment]
Hi, you can take any of the modules, and check that it works on new version, or modify the code to make it work, and the publish a PR with these changes.

**Comment by odooerpperu** [comment]
Please  need the module : pos_sequence_ref_number v8 modify to v9 or v10 
thank
