### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by sbidoul** [OCA/pos#849]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

# Modules to migrate

- [x] pos_access_right - By @geomer198 - #957
- [ ] pos_cash_move_reason - By @quentinDupont - #1420
- [ ] pos_customer_display - By @legalsylvain - #1159
- [x] pos_customer_tree_view_vat - By @chienandalu - #1221
- [x] pos_default_partner - By @alv97 - #853
- [ ] pos_edit_order_line - By @flachica - #926
- [x] pos_escpos_status - By @nwinkelstraeter - #910
- [ ] pos_event_sale - By @BT-dmoreno - #1022
- [ ] pos_event_sale_registration_qr_code
- [x] pos_hide_banknote_button - By @legalsylvain - #1173
- [ ] pos_hide_cost_price_and_margin
- [ ] pos_hide_empty_category - By @legalsylvain - #1511
- [x] pos_hide_partner_info - By @huguesdk - #1354
- [x] pos_journal_image - By @legalsylvain - #1021
- [ ] pos_lot_barcode - By @yankinmax - #934
- [ ] pos_lot_selection - By @yankinmax - #935
- [ ] pos_margin_account_invoice_margin - By @legalsylvain - #1128
- [ ] pos_order_remove_line - By @suker - #925
- [x] pos_order_to_sale_order - By @legalsylvain - #854
- [x] pos_partner_firstname - By @victor-champonnois - #1027
- [x] pos_partner_no_create - By @mihien - #1422
- [ ] pos_payment_change - By @julenfl - #929
- [x] pos_payment_method_cashdro - By @chienandalu - #1161
- [x] pos_payment_terminal - By @nwinkelstraeter - #908
- [x] pos_picking_delayed - By @em230418 - #1227
- [x] pos_picking_load - By @HeliconiaSolutions - #1266
- [x] pos_price_to_weight - By @legalsylvain - #1146
- [x] pos_pricelist_technical - By @legalsylvain - #1130
- [ ] pos_product_display_default_code - By @suker - #927
- [x] pos_product_mergeable_line - By @legalsylvain - #1145
- [x] pos_product_multi_barcode - By @nguyenminhchien - #1037
- [ ] pos_product_template - By @zurabkituashvili - #1204
- [x] pos_receipt_hide_price - By @danielduqma - #851
- [x] pos_report_session_summary - By @carlos-lopez-tecnativa - #1229
- [x] pos_require_product_quantity - By @mihien - #1438
- [x] pos_reset_search - By @victor-champonnois - #1030
- [ ] pos_sale_pos_event_sale
- [x] pos_session_pay_invoice - By @carlos-lopez-tecnativa - #1226
- [x] pos_supplierinfo_search - By @carlos-lopez-tecnativa - #1225
- [x] pos_tare - By @huguesdk - #1323
- [ ] pos_ticket_extra_company_info - By @legalsylvain - #1131
- [x] pos_timeout - By @benwillig - #1148
- [x] pos_to_weight_by_product_uom - By @legalsylvain - #1127
- [ ] pos_product_template - By @papulo79 - #1170

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list

**Comment by danielduqma** [comment]
Migration of `pos_receipt_hide_price` from 14.0 made in #851

**Comment by alv97** [comment]
Migration of pos_default_partner from 14.0 made in https://github.com/OCA/pos/pull/853

**Comment by alexis-via** [comment]
No need to port pos_no_cash_bank_statement from v14 to v16. According to my tests, Odoo v16 generate by default accounting entries no only for cash journals but also for bank journals. It seems Odoo SA changed their mind again... good move this time :)

**Comment by legalsylvain** [comment]
Hi @alexis-via. Thanks for your remark. One question, the feature is native in which module (account, other ?), and since which release (15 / 16) ? 
if the feature is native, I'll do a PR against openupgrade in the apriori file. (merged_modules section).

thanks for your reply.

**Comment by nwinkelstraeter** [comment]
Migration of `pos_payment_terminal` from 14.0 in #908 which is still missing from this list.
`pos_escpos_status` is also missing, which I would also like to migrate

**Comment by alexis-via** [comment]
About account move generation on POS v16: I made more tests, and I confirm that bank statement generation works well, but I have another problem: in v14, the boolean field "split_transactions" on pos_payment_method had a string "Split Transactions". In v16, this boolean field still exists, but it's string is "Identify Customer", so, if you enable it, it will not only split transactions but also force you to select a customer.
I will probably develop a module to be able to split transactions without obliging to select a customer ; I need it for payment by check.
FYI, I'll have to develop that before 31/12/2022

**Comment by legalsylvain** [comment]
> In v16, this boolean field still exists, but it's string is "Identify Customer", so, if you enable it, it will not only split transactions but also force you to select a customer.

wow ! definitively, V16 looks not finished ! Please ping me when your module is ready.

And regarding my previous remark. Is pos_no_cash_bank_statement unnecessary in V15 or in V16 ?

thanks.

**Comment by nwinkelstraeter** [comment]
Migration of `pos_escpos_status` from 14.0 in #910

**Comment by alexis-via** [comment]
As promised, I worked on having 2 booleans fields on pos.payment.method:
- keep the native "split_transaction" ONLY to split the transactions
- add a second boolean "identify_customer" to oblige to select a customer
As I found it too difficult to develop it via inheritence, I wrote a module "pos_check_deposit" https://github.com/akretion/odoo-usability/tree/16.0/pos_check_deposit that requires to apply a patch on the point_of_sale module of Odoo, that's why I didn't submit this module to OCA. Unfortunately, the patch is bigger than I thought (see file odoo-pos_check_deposit.diff at the root directory of the module) because in the generation of the account.move.line when closing the POS session, when split_transaction is enabled, Odoo always consider that a partner has been selected, so I had to patch 3 methods in pos.session that handle the generation and reconciliation of the account.move.line.

Another idea would be to be able to configure a "default partner" on a pos.payment.method ; when selecting a payment method in the POS frontend, if no customer has been selected yet, Odoo would automatically select this "default partner" as customer. That way, on the "Check" POS payment method, you would set the "default partner" to a generic "POS Check". Advantages:
- no need to modify the code that generate the account.move.lines.
- the cashier doesn't spend time creating/selection a partner when a customer pays by check
I don't plan to write that module myself in the short term, so feel free to do it if you think this idea is good.

@legalsylvain I confirm that pos_no_cash_bank_statement is not needed in v16.

**Comment by suker** [comment]
Migration of `pos_order_remove_line` from 14.0 made in https://github.com/OCA/pos/pull/925

**Comment by flachica** [comment]
Migration of `pos_edit_order_line` from 14.0 #926

**Comment by suker** [comment]
@sbidoul pre-commit needs to be update, pipeline are failing:
```
repo: https://github.com/PyCQA/isort
   rev: 5.10.1
```
to
```
repo: https://github.com/PyCQA/isort
   rev: 5.12.0
```

**Comment by rousseldenis** [comment]
> @sbidoul pre-commit needs to be update, pipeline are failing:
> 
> ```
> repo: https://github.com/PyCQA/isort
>    rev: 5.10.1
> ```
> 
> to
> 
> ```
> repo: https://github.com/PyCQA/isort
>    rev: 5.12.0
> ```

@suker The errors you have there : https://github.com/OCA/pos/pull/925 are real errors. You have to solve them

**Comment by suker** [comment]
Migration of `pos_product_display_default_code` from 15.0 #927

**Comment by julenfl** [comment]
Migration of pos_payment_change from 15.0 #929

**Comment by yankinmax** [comment]
@sbidoul @ivantodorovich I've opened new migration PRs for `pos_lot_barcode` and `pos_lot_selection` to supersede existing ones which needs fixing.
Old ones:
- [ ] https://github.com/OCA/pos/pull/918
- [ ] https://github.com/OCA/pos/pull/917

New ones with tests green:
- [ ] https://github.com/OCA/pos/pull/934
- [ ] https://github.com/OCA/pos/pull/935

**Comment by berteh** [comment]
please kindly add pos_tare to the modules that still need migration to 16.0.

**Comment by raulovallet** [comment]
why pos_report_session_summary is not here?

**Comment by carlos-lopez-tecnativa** [comment]
pos_supplierinfo_search on https://github.com/OCA/pos/pull/1225

**Comment by hmgsoftware** [comment]
regarding `pos_product_template`:
pls replace #1204 with #1170 which passed all checks

**Comment by Daniel-Melian** [comment]
why pos_user_restriction is not here?

**Comment by ivantodorovich** [comment]
Hello @Daniel-Melian ,

Only modules that were in the `15.0` at the time this issue is created are added automatically.
It seems `pos_user_restriction` was migrated and merged after that, and that's why it isn't here.

More about this: https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list

**Comment by BhaveshHeliconia** [comment]
pos_picking_load: [#1266](https://github.com/OCA/pos/pull/1266)

**Comment by BhaveshHeliconia** [comment]
Working on

pos_show_clock

**Comment by ferdymercury** [comment]
> please kindly add pos_tare to the modules that still need migration to 16.0.

See https://github.com/OCA/pos/pull/1323
